# Generated by Django 3.2 on 2023-12-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_open', models.DateTimeField(auto_now_add=True)),
                ('date_close', models.DateTimeField(blank=True, null=True)),
                ('open_price', models.DecimalField(decimal_places=5, max_digits=18)),
                ('close_price', models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True)),
                ('alpha', models.IntegerField()),
                ('net_profit', models.DecimalField(blank=True, decimal_places=5, max_digits=18, null=True)),
                ('sl', models.DecimalField(decimal_places=5, max_digits=18)),
                ('tp', models.DecimalField(decimal_places=5, max_digits=18)),
            ],
        ),
    ]
