# Generated by Django 4.2.8 on 2023-12-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Closed', max_length=10),
        ),
    ]
