# Generated by Django 4.2.8 on 2024-03-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_priority",
            new_name="priority",
        ),
    ]
