# Generated by Django 4.2.8 on 2024-03-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_rename_is_priority_user_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tokens",
            field=models.IntegerField(default=0),
        ),
    ]
