# Generated by Django 4.2.8 on 2024-03-20 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("default_hyperparameters", models.JSONField()),
                ("default_model_architecture", models.TextField()),
                ("default_training_configuration", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="TrainedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("training_timestamp", models.DateTimeField()),
                ("performance_metrics", models.JSONField()),
                ("hyperparameters", models.JSONField()),
                ("model_architecture", models.TextField()),
                ("serialized_model", models.BinaryField()),
                ("training_logs", models.TextField()),
                ("status", models.CharField(max_length=25)),
                (
                    "model_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="model_core.modeltype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
