# Generated by Django 4.2.8 on 2024-03-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("model_core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modeltype",
            name="default_training_configuration",
        ),
        migrations.RemoveField(
            model_name="trainedmodel",
            name="description",
        ),
    ]
