# Generated by Django 4.2.8 on 2024-04-01 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("evaluation_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("model_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Queue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("priority", models.BooleanField(default=False)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluation_core.asset",
                    ),
                ),
                (
                    "model_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="model_core.modeltype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "created_at"],
            },
        ),
    ]
